version: '3.8'

services:
  macm-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: macm-agent-tools-api
    ports:
      - "8080:8080"
    environment:
      - PYTHONPATH=/app/src
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    volumes:
      # Mount catalogs for live updates (optional)
      - ./catalogs:/app/catalogs:ro
      # Mount source for development (uncomment for dev mode)
      # - ./src:/app/src:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8080/api/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - macm-network

networks:
  macm-network:
    driver: bridge
    name: macm-network