version: '3.8'

services:
  macm-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: macm-agent-tools-api
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      # Mount catalogs for live updates (optional)
      - ./catalogs:/app/src/catalogs:ro
      # Mount source for development (uncomment for dev mode)
      # - ./src:/app/src:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8080/api/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - macm-network
    depends_on:
      - neo4j

  neo4j:
    image: neo4j:5.15-community
    container_name: macm-neo4j
    environment:
      - NEO4J_AUTH=neo4j/macmpassword
      - NEO4J_PLUGINS=["apoc", "apoc-extended"]
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_default__database=macm
    volumes:
      - ./neo4j/config:/conf
      - ./neo4j/init:/var/lib/neo4j/db_init
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "macmpassword", "RETURN 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - macm-network

networks:
  macm-network:
    driver: bridge
    name: macm-network