version: '3.8'

services:
  macm-api-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: macm-agent-tools-api-dev
    ports:
      - "8080:8080"
    environment:
      - PYTHONPATH=/app/src
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    volumes:
      # Mount source code for hot reload during development
      - ./src:/app/src:ro
      - ./catalogs:/app/catalogs:ro
    restart: unless-stopped
    command: ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]
    working_dir: /app/src
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8080/api/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - macm-network

networks:
  macm-network:
    driver: bridge
    name: macm-network